# Generated by Django 2.0 on 2018-06-01 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0002_remove_userwordlist_lexicon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedlexicon',
            name='word',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='card.Word'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customizedlexicon',
            name='words',
        ),
        migrations.AlterUniqueTogether(
            name='customizedlexicon',
            unique_together={('user', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'belong')},
        ),
    ]
