# Generated by Django 2.0 on 2018-06-02 03:45

import card.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0003_auto_20180601_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=50, validators=[card.models.validate_range])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userplan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userwordlist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userwordlist',
            name='count',
            field=models.IntegerField(default=0, validators=[card.models.validate_range]),
        ),
    ]
