# Generated by Django 2.0 on 2018-06-02 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20180602_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='id',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userplan', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
