# Generated by Django 2.0 on 2018-06-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20180602_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordlist',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
