# Generated by Django 2.0 on 2018-06-02 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20180602_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordlist',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
