# Generated by Django 2.0 on 2018-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_userwordlist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userwordlist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
